define(["esri/dijit/_EventedWidget","dojo/on","dojo/mouse","dojo/aspect","dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Deferred","dojo/number","dijit/registry","dijit/_WidgetBase","dijit/_OnDijitClickMixin","dijit/_TemplatedMixin","dijit/_WidgetsInTemplateMixin","dojo/dom-geometry","dojo/_base/Color","dojox/charting/Chart","dojox/charting/axis2d/Default","dojox/charting/plot2d/Grid","dojox/charting/plot2d/Markers","dojox/charting/plot2d/Areas","dojox/charting/action2d/MouseIndicator","dojox/charting/action2d/TouchIndicator","dojox/charting/themes/ThreeD","dojox/charting/SimpleTheme","dojox/charting/widget/SelectableLegend","esri/config","esri/sniff","esri/request","esri/graphic","esri/layers/ArcGISImageServiceLayer","esri/layers/ImageServiceParameters","esri/layers/GraphicsLayer","esri/layers/DimensionalDefinition","esri/layers/RasterFunction","dojo/i18n!../../nls/jsapi","dojo/text!./templates/DimensionalProfile.html","xstyle/css!./css/MultiDimensionalProfile.css"],function(_EventedWidget,on,mouse,aspect,declare,lang,array,Deferred,number,registry,WidgetBase,_OnDijitClickMixin,_TemplatedMixin,_WidgetsInTemplateMixin,domGeometry,Color,Chart,Default,Grid,Markers,Areas,MouseIndicator,TouchIndicator,ThreeD,SimpleTheme,SelectableLegend,esriConfig,esriSniff,esriRequest,Graphic,ArcGISImageServiceLayer,ImageServiceParameters,GraphicsLayer,DimensionalDefinition,RasterFunction,jsapiBundle,dimensionalProfileTemplate){return declare([WidgetBase,_OnDijitClickMixin,_TemplatedMixin,_WidgetsInTemplateMixin],{declaredClass:"esri.dijit.MultiDimensionalProfile",baseClass:"esriMultiDimensionalChart",templateString:dimensionalProfileTemplate,SERIES_NAME_DIMENSIONS:"Dimensions",SERIES_NAME_LEGEND:"Point",_samplingDataCount:50,_reduceDataPoints:true,_chartRenderingOptions:null,_defaultXAxisRange:{min:Number.MAX_VALUE,max:Number.MIN_VALUE},_defaultYAxisRange:{min:0.0,max:100.0},_xAxisRange:null,_yAxisRange:null,_profileResults:[],_maxResultCount:4,_map:null,_layers:[],_dimension:null,_variable:null,_chart:null,_valueIndicator:[],_drawProfileGeometry:true,_mapGraphics:[],_chartLocationGraphic:null,_posIndicator:null,_negIndicator:null,_chartLocationGraphicsLayer:null,_defaultMapSymbol:{type:"esriSMS",style:"esriSMSCross",color:[0,0,0,0],size:13,angle:0,xoffset:0,yoffset:0,outline:{type:"esriSLS",style:"esriSLSSolid",color:[0,0,0,255],width:3}},_profileSeries:[{stroke:"#ff00a9",fill:""},{stroke:"#00ff00",fill:""},{stroke:"#ff5722",fill:""},{stroke:"#0900ff",fill:""},{stroke:"#845422",fill:""},{stroke:"#6C618D",fill:""}],constructor:function(options,srcRefNode){this._layers=[];this._i18n=jsapiBundle;if(options.hasOwnProperty("map")){this._map=options.map;}
if(options.hasOwnProperty("layers")){options.layers.forEach(function(layerObj){var options=this._updateLayerOptions(layerObj);layerObj.options=options;this._layers.push(layerObj);}.bind(this));}
if(this._layers.length>1){this._maxResultCount=this._layers.length;}
if(options.hasOwnProperty("dimension")){this._dimension=options.dimension;}
if(options.hasOwnProperty("variable")){this._variable=options.variable;}
if(options.hasOwnProperty("drawGraphicOnMap")){this._drawGraphicOnMap=options.drawGraphicOnMap;}
this._chartRenderingOptions=lang.mixin({xAxisTitle:"X",yAxisTitle:"Y",chartFontFamily:"verdana",chartTitleFontSize:13,axisTitleFontSize:11,axisLabelFontSize:9,indicatorFontColor:"#eee",indicatorFillColor:"#666",titleFontColor:"#eee",axisFontColor:"#ccc",axisMajorTickColor:"#333",profileBackgroundTopColor:[250,250,250,0.8],profileBackgroundBottomColor:[229,230,235,0.7],profileLineColor:"#D2B48C",profileTopColor:"#8B4513",profileBottomColor:"#CD853F",indicatorMarkerStrokeColor:"#FF0000",indicatorMarkerSymbol:"m -6 -6, l 12 12, m 0 -12, l -12 12",profileGeometrySymbol:this._defaultMapSymbol},options.chartOptions||{});},postCreate:function(){this.inherited(arguments);if(registry.getEnclosingWidget(this.domNode)!==null){this.own(aspect.after(registry.getEnclosingWidget(this.domNode),"resize",lang.hitch(this,this.resize),true));}},startup:function(){this.inherited(arguments);if(!this._map||!this._layers.length||!this._dimension){this.emit("error",new Error(this._i18n.widgets.DimensionalProfile.errors.MissingInputParameters));this.destroy();}
else{if(this.map.loaded){this._initProfile();}
else{this.map.on("load",this._initProfile.bind(this));}}},clear:function(){this._displayChartLocation(-1);this._clearProfileGeometriesOnMap();this._resetProfileResults();this._clearIndicators();this._clearChart();this.emit("clear");},refresh:function(){this.emit("refresh");},update:function(profileResult){if(!profileResult){this.emit(new Error(this._i18n.widgets.DimensionalProfile.errors.InvalidProfileResults));return;}
var mProfileResult=this._reduceProfileResults(lang.mixin({},profileResult));this._updateProfileResults(mProfileResult);this._updateChart(mProfileResult);this._updateGraphic(mProfileResult);this._updateIndicators();this.emit("update",mProfileResult);},resize:function(){this.inherited(arguments);if(this._chart){this._chart.resize();}},destroy:function(){if(this._chart){this._chart.destroy();}
this.inherited(arguments);},_updateLayerOptions:function(layerObj){if(!layerObj||!layerObj.options){return{};}
var options=lang.mixin({},layerObj.options);var renderingRule=layerObj.options.renderingRule;if(renderingRule){var rFunction=new RasterFunction(renderingRule);rFunction.functionName=renderingRule;options.renderingRule=rFunction;}
return options;},_setProfileGeometryAttr:function(geometry){if(geometry){this._map.setMapCursor("progress");this._layers.forEach(lang.hitch(this,function(layerObj){var graphic=this._createNewMapGraphic(geometry);this._drawProfileGeometryOnMap(graphic);this._getProfile(layerObj,graphic).then(lang.hitch(this,function(profileResult){this._map.setMapCursor("default");this.update(profileResult);}),lang.hitch(this,function(error){this._map.setMapCursor("default");this.emit("error",error);}));}));}
else{this.emit("error",new Error(this._i18n.widgets.DimensionalProfile.errors.NullGeometry));}},_setTitleAttr:function(title){if(!this._chart){return;}
this._chart.title=title;this._chart.dirty=true;this._chart.render();this.emit("title-changed");},_resetProfileResults:function(){this._xAxisRange=lang.mixin({},this._defaultXAxisRange);this._yAxisRange=lang.mixin({},this._defaultYAxisRange);this._profileResults=[];},_initProfile:function(){this._buildProfileSeries();this._getDefaultDimensionalRange().then(function(result){this._defaultXAxisRange=result;this._resetProfileResults();this._buildChart();this.emit("load");}.bind(this));},_buildProfileSeries:function(){var sIdx=0,cIdx=-1,orgProfileSeries=JSON.parse(JSON.stringify(this._profileSeries)),useComparisonSeries=(this._layers.length===2);var layerProperties=this._layers[0].options,layerLegend,layerLegend0,layerLegend1,seriesColor,seriesColor0,seriesColor1;layerLegend=layerLegend0=layerProperties&&layerProperties.legendLabel;seriesColor=seriesColor0=layerProperties&&layerProperties.seriesColor;if(useComparisonSeries){var layerProperties1=this._layers[1].options;layerLegend1=layerProperties1&&layerProperties1.legendLabel;seriesColor1=layerProperties1&&layerProperties1.seriesColor;}
for(sIdx;sIdx<this._maxResultCount;sIdx++){if(sIdx<this._profileSeries.length&&useComparisonSeries){layerLegend=Math.abs(sIdx%2)===0?layerLegend0:layerLegend1;seriesColor=Math.abs(sIdx%2)===0?seriesColor0:seriesColor1;}else if(sIdx<this._profileSeries.length&&!useComparisonSeries&&layerLegend0){layerLegend=layerLegend0+" "+sIdx;}else if(sIdx>=this._profileSeries.length){var rColor='#'+Math.floor(Math.random()*16777215).toString(16);this._profileSeries.push({stroke:rColor,fill:""});}
if(seriesColor){this._profileSeries[sIdx].stroke=seriesColor;}
this._profileSeries[sIdx].name=this.SERIES_NAME_DIMENSIONS+"_"+sIdx;this._profileSeries[sIdx].legend=layerLegend||(this.SERIES_NAME_LEGEND+" "+sIdx);}},_buildChart:function(){var newChart=new Chart(this._chartNode,{title:this._chartRenderingOptions.title,titlePos:"top",titleGap:10,titleFont:lang.replace("normal normal bold {chartTitleFontSize}pt {chartFontFamily}",this._chartRenderingOptions),titleFontColor:this._chartRenderingOptions.titleFontColor});if(this._layers.length===2){var myTheme=new SimpleTheme({markers:{CIRCLE:"m-3,0 c0,-4 6,-4 6,0 m-6,0 c0,4 6,4 6,0",SQUARE:"m-3,-3 l0,6 6,0 0,-6 z"}});newChart.setTheme(myTheme);}else{newChart.setTheme(ThreeD);}
newChart.fill="transparent";newChart.theme.axis.stroke.width=2;newChart.theme.axis.majorTick.color=Color.named.white.concat(0.5);newChart.theme.axis.majorTick.width=1.0;newChart.theme.plotarea.fill={type:"linear",space:"plot",x1:50,y1:100,x2:50,y2:0,colors:[{offset:0.0,color:this._chartRenderingOptions.profileBackgroundTopColor},{offset:1.0,color:this._chartRenderingOptions.profileBackgroundBottomColor}]};newChart.addAxis("y",{min:this._yAxisRange.min,max:this._yAxisRange.max,fontColor:this._chartRenderingOptions.axisFontColor,font:lang.replace("normal normal bold {axisLabelFontSize}pt {chartFontFamily}",this._chartRenderingOptions),vertical:true,natural:true,fixed:true,includeZero:false,majorLabels:true,minorLabels:true,majorTicks:true,minorTicks:true,majorTick:{color:this._chartRenderingOptions.axisMajorTickColor,length:6},title:this._chartRenderingOptions.yAxisTitle,titleGap:30,titleFont:lang.replace("normal normal bold {axisTitleFontSize}pt {chartFontFamily}",this._chartRenderingOptions),titleFontColor:this._chartRenderingOptions.titleFontColor,titleOrientation:"axis"});newChart.addAxis("x",{min:this._xAxisRange.min,max:this._xAxisRange.max,fontColor:this._chartRenderingOptions.axisFontColor,font:lang.replace("normal normal bold {axisLabelFontSize}pt {chartFontFamily}",this._chartRenderingOptions),natural:true,fixed:true,includeZero:false,majorLabels:true,minorLabels:true,majorTicks:true,minorTicks:true,majorTick:{color:this._chartRenderingOptions.axisMajorTickColor,length:6},title:this._chartRenderingOptions.xAxisTitle,titleGap:5,titleFont:lang.replace("normal normal bold {axisTitleFontSize}pt {chartFontFamily}",this._chartRenderingOptions),titleFontColor:this._chartRenderingOptions.titleFontColor,titleOrientation:"away",labelFunc:lang.hitch(this,this._formatChartValues)});newChart.addPlot("grid",{type:Grid,hMajorLines:true,hMinorLines:false,vMajorLines:false,vMinorLines:false});newChart.addPlot("default",{type:Markers,tension:"X"});var seriesOptions={plot:"default",stroke:{width:1.5,color:this._chartRenderingOptions.profileLineColor},fill:this._chartRenderingOptions.profileTopColor};var sIdx=0;for(sIdx;sIdx<this._maxResultCount;sIdx++){var mSeriesOptions=lang.clone(seriesOptions);mSeriesOptions.stroke.color=this._profileSeries[sIdx].stroke;mSeriesOptions.fill=this._profileSeries[sIdx].stroke;mSeriesOptions.legend=this._profileSeries[sIdx].legend;newChart.addSeries(this._profileSeries[sIdx].name,[],mSeriesOptions);}
newChart.render();var chartLegend=new SelectableLegend({chart:newChart,autoScale:true},this._chartLegendNode);this._chart=newChart;this._chartLegend=chartLegend;},_formatChartValues:function(text,value){if(this._dimension&&this._dimension.toLowerCase()==="stdtime"){return new Date(value).toUTCString().substring(5,16);}
return value;},_chartTooltipForX:function(value,options){var dimString=value.x;if(this._dimension&&this._dimension.toLowerCase()==="stdtime"){dimString=new Date(value.x).toUTCString().substring(5,16);}
return this._chartRenderingOptions.xAxisTitle+": "+dimString;},_chartTooltipForY:function(value){var valY=(value.y&&typeof value.y==="string")?parseFloat(value.y):value.y;return this.label+": "+valY.toFixed(3);},_getProfile:function(layerObj,graphic){var layer=layerObj.layer;var geometry=graphic&&graphic.geometry;var geometryType="esriGeometryPoint";if(!layer||!graphic||!geometry){return new Error(this.strings.errors.UnableToProcessResults);}
var identifyRequest={f:"json",geometry:JSON.stringify(geometry.toJson()),geometryType:geometryType,returnGeometry:false,returnCatalogItems:true};var layerProperties=layerObj.options;var mosaicRule=layer.mosaicRule||layer.defaultMosaicRule;if(layerProperties.variable&&mosaicRule){var mRule=lang.clone(mosaicRule);mRule.multidimensionalDefinition.push(new DimensionalDefinition({variableName:layerProperties.variable}));identifyRequest.mosaicRule=JSON.stringify(mRule.toJson());}
var tagsToSearch=["value"];var renderingRule=(layerProperties&&layerProperties.renderingRule)||layer.renderingRule;if(renderingRule){tagsToSearch.push(renderingRule.functionName.toLowerCase());identifyRequest.renderingRule=JSON.stringify(renderingRule.toJson());}
var useMapTime=(layerProperties&&layerProperties.hasOwnProperty("useMapTime"))?layerProperties.useMapTime:layer.useMapTime;if(useMapTime&&this._map.timeExtent){identifyRequest.time=this._map.timeExtent.toJson().join(",");}
return esriRequest({url:layer.url+"/identify",handleAs:"json",content:identifyRequest}).then(lang.hitch(this,function(results){if(!results||results.catalogItems.length<1){return;}
var profileFeatures=results.catalogItems.features;var dimensionValues=[];var layerVariable=this._getLayerVariable(layer);array.forEach(profileFeatures,function(feature,idx){var pixelValue=results.properties.Values[idx];var attr=feature.attributes;if(pixelValue&&pixelValue.toLowerCase()!=="nodata"&&(!layerVariable||attr.Variable.toLowerCase()===layerVariable.toLowerCase())){var dimValue={x:attr[this.dimension],y:pixelValue};dimensionValues.push(dimValue);}}.bind(this));return{values:dimensionValues,graphic:graphic};}),lang.hitch(this,function(){return new Error(this.strings.errors.UnableToProcessResults);}));},_updateProfileResults:function(profileResult){if(!profileResult){return;}
if(this._profileResults.length===this._profileSeries.length){profileResult.series=this._profileResults[0].series;this._profileResults.shift();}else{profileResult.series=this._profileSeries[this._profileResults.length];}
profileResult.values.sort(function(val1,val2){return(val1.x-val2.x);});this._profileResults.push(profileResult);var defAxisRange={min:Number.MAX_VALUE,max:Number.MIN_VALUE};var xAxisRange,yAxisRange;xAxisRange=lang.mixin({},defAxisRange);yAxisRange=lang.mixin({},defAxisRange);array.forEach(this._profileResults,function(result){var minX=this._getArrayMin(result.values,"x");var maxX=this._getArrayMax(result.values,"x");var minY=this._getArrayMin(result.values,"y");var maxY=this._getArrayMax(result.values,"y");xAxisRange.min=minX<xAxisRange.min?minX:xAxisRange.min;xAxisRange.max=maxX>xAxisRange.max?maxX:xAxisRange.max;yAxisRange.min=minY<yAxisRange.min?minY:yAxisRange.min;yAxisRange.max=maxY>yAxisRange.max?maxY:yAxisRange.max;}.bind(this));this._xAxisRange=xAxisRange;this._yAxisRange=yAxisRange;this._yAxisRange.min=yAxisRange.min-(0.03*yAxisRange.min);this._yAxisRange.max=yAxisRange.max+(0.03*yAxisRange.max);},_updateChart:function(profileResult){if(!this._chart){return;}
this._chart.getAxis("x").opt.min=this._xAxisRange.min;this._chart.getAxis("x").opt.max=this._xAxisRange.max;this._chart.getAxis("y").opt.min=this._yAxisRange.min;this._chart.getAxis("y").opt.max=this._yAxisRange.max;this._chart.dirty=true;if(profileResult){var seriesName=profileResult.series.name;this._chart.updateSeries(seriesName,profileResult.values);}
this._chart.render();this._chartLegend.refresh();},_clearChart:function(){if(!this._chart){return;}
var i;for(i=0;i<this._chart.series.length;i++){this._chart.updateSeries(this._chart.series[i].name,[]);}
this._chart.render();this._chartLegend.refresh();},_clearIndicators:function(){if(this._valueIndicator){array.forEach(this._valueIndicator,function(vIndicator){vIndicator.destroy();vIndicator=null;});this._valueIndicator=[];}},_updateIndicators:function(){if(this._chart){this._clearIndicators();var detailsNumberFormat={places:1};var valueIndicatorProperties={mouseOver:true,font:"normal normal bold 8pt Tahoma",fontColor:this._chartRenderingOptions.indicatorFontColor,fill:this._chartRenderingOptions.indicatorFillColor,markerFill:"none",markerStroke:{color:this._chartRenderingOptions.indicatorMarkerStrokeColor,width:3.0},markerSymbol:this._chartRenderingOptions.indicatorMarkerSymbol};var xIndicatorProperties={series:this.SERIES_NAME_DIMENSIONS+"_0",start:true,offset:{y:0,x:0},labelFunc:lang.hitch(this,this._chartTooltipForX)};if(esriSniff("has-touch")){}
else{var sIdx=0;var yOffset=20;for(sIdx;sIdx<this._profileResults.length;sIdx++){var seriesLegend=this._getSeriesLegend(this.SERIES_NAME_DIMENSIONS+"_"+sIdx);var labelInfo={label:seriesLegend||this._chartRenderingOptions.yAxisTitle};var yIndicatorProperties={labelFunc:lang.hitch(labelInfo,this._chartTooltipForY)};var indicatorProperties=lang.mixin({series:this.SERIES_NAME_DIMENSIONS+"_"+sIdx,offset:{x:10,y:yOffset*(sIdx+1)}},yIndicatorProperties,valueIndicatorProperties);this._valueIndicator.push(new MouseIndicator(this._chart,"default",indicatorProperties));}}
this._chart.fullRender();}},_getSeriesLegend:function(seriesName){var series=this._chart.getSeries(seriesName);return series?series.legend:"";},_createNewMapGraphic:function(geometry){if(!this._map||!geometry){return;}
var indicatorSymbol=this._chartRenderingOptions.profileGeometrySymbol;var mapSymbol=indicatorSymbol.hasOwnProperty("type")?indicatorSymbol:indicatorSymbol.toJson();if(mapSymbol.type!=="esriSMS"&&mapSymbol.type!=="esriPMS"){mapSymbol=this._defaultMapSymbol;}
var newGraphic=new Graphic({geometry:geometry,symbol:mapSymbol});return newGraphic;},_drawProfileGeometryOnMap:function(graphic){if(!this._map||!graphic||!this._drawProfileGeometry){return;}
if(this._mapGraphics.length===this._maxResultCount){var oldestGraphic=this._mapGraphics[0];this._map.graphics.remove(oldestGraphic);this._mapGraphics.shift();}
this._mapGraphics.push(graphic);this._map.graphics.add(graphic);},_updateGraphic:function(profileResult){if(!profileResult||!profileResult.graphic){return;}
var graphic=profileResult.graphic,series=profileResult.series;if(series){graphic.symbol.color=new Color(series.stroke);graphic.symbol.outline.color=new Color(series.stroke);graphic.draw();}},_clearProfileGeometriesOnMap:function(){if(!this._mapGraphics){return;}
array.forEach(this._mapGraphics,function(graphic){this._map.graphics.remove(graphic);}.bind(this));this._mapGraphics=[];},_displayChartLocation:function(chartObjectX){if(this._map&&this._profileResults.values&&this._profileResults.geometry){if(!this._chartLocationGraphic){var indicatorSymbol=this._chartRenderingOptions.mapIndicatorSymbol;var mapSymbol=indicatorSymbol.hasOwnProperty("type")?indicatorSymbol:indicatorSymbol.toJson();if(mapSymbol.type!=="esriSMS"&&mapSymbol.type!=="esriPMS"){mapSymbol=this._defaultMapSymbol;}
this._chartLocationGraphic=new Graphic({geometry:null,symbol:mapSymbol});if(!this._chartLocationGraphicsLayer){this._chartLocationGraphicsLayer=new GraphicsLayer();this._map.addLayer(this._chartLocationGraphicsLayer);}
this._chartLocationGraphicsLayer.add(this._chartLocationGraphic);}}},_reduceProfileResults:function(profileResult){var values=profileResult.values;if(!this._reduceDataPoints||values.length<(3*this._samplingDataCount)){return profileResult;}
var reducedValues=[];var factor=this._samplingDataCount/3;var size=Math.ceil((values.length)/factor),i=0,minIdx,maxIdx,minX,minY,maxX,maxY,meanX,meanY;for(i=0;i<size;i++){minIdx=(i===0)?(i*factor):(i*factor)+1;maxIdx=(i+1)*factor;minX=this._getArrayMin(values.slice(minIdx,maxIdx),"x");maxX=this._getArrayMax(values.slice(minIdx,maxIdx),"x");minY=this._getArrayMin(values.slice(minIdx,maxIdx),"y");maxY=this._getArrayMax(values.slice(minIdx,maxIdx),"y");meanX=(minX+maxX)/2;meanY=(minY+maxY)/2;reducedValues.push({"x":meanX,"y":meanY});}
profileResult.values=reducedValues;return profileResult;},_getArrayMax:function(dataArray,property){var values=array.map(dataArray,function(item){return item[property];});return Math.max.apply(Math,values);},_getArrayMin:function(dataArray,property){var values=array.map(dataArray,function(item){return item[property];});return Math.min.apply(Math,values);},_getLayerVariable:function(layer){var layerVariable=null;if(layer&&layer.mosaicRule&&layer.mosaicRule.multidimensionalDefinition&&layer.mosaicRule.multidimensionalDefinition.length){layerVariable=layer.mosaicRule.multidimensionalDefinition[0].variableName;}
return layerVariable;},_getDefaultDimensionalRange:function(){var layer=this._layers[0].layer;if(!layer){return;}
var layerVariable=this._getLayerVariable(layer);var val={min:0.0,max:100.0};return layer.getMultidimensionalInfo().then(function(result){var mdInfo=result;if(mdInfo&&mdInfo.variables&&mdInfo.variables.length&&layerVariable){array.forEach(mdInfo.variables,function(variable){if(variable.name.toLowerCase()===layerVariable.toLowerCase()){array.forEach(variable.dimensions,function(dim){if(dim.name.toLowerCase()===this.dimension.toLowerCase()&&dim.extent&&dim.extent.length===2){val.min=dim.extent[0];val.max=dim.extent[1];}}.bind(this));}}.bind(this));}
return val;}.bind(this),function(error){console.log(error);return val;});}});});